#!/usr/bin/env python3
"""firmware/tools/make_model_stats.py -- regenerate main/sentinel_model_stats.h from
model/artifacts_sim/sentinel_model_header.json (mean/scale standardisation vectors +
conformal offsets). Companion to gen_golden.py; run it whenever the model artifacts are
regenerated (model/ is a separate, independently-owned module -- see firmware/README.md
"what was executed here" for the snapshot this repo's firmware/ was last synced against).

    python3 firmware/tools/make_model_stats.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER_JSON = ROOT / "model" / "artifacts_sim" / "sentinel_model_header.json"
OUT = Path(__file__).resolve().parents[1] / "main" / "sentinel_model_stats.h"


def femit(name, arr):
    vals = ", ".join(("nanf(\"\")" if isinstance(v, float) and math.isnan(v) else "%.9ff" % v) for v in arr)
    return "static const float %s[%d] = {%s};" % (name, len(arr), vals)


def main():
    h = json.loads(HEADER_JSON.read_text())
    ms = h["mean_scale"]
    co = h["conformal_offsets"]
    gt = h["grade_thresholds"]

    lines = []
    lines.append("/* AUTO-GENERATED by firmware/tools/make_model_stats.py from")
    lines.append(" * model/artifacts_sim/sentinel_model_header.json -- do not hand-edit.")
    lines.append(" * feature_schema_version=%d (must match features/schema.py, checked at" % h["feature_schema_version"])
    lines.append(" * boot per design 04 §4 step 3). */")
    lines.append("#ifndef SENTINEL_MODEL_STATS_H")
    lines.append("#define SENTINEL_MODEL_STATS_H")
    lines.append("")
    lines.append("#include <math.h>")
    lines.append("")
    lines.append("#define SENTINEL_MODEL_FEATURE_SCHEMA_VERSION %d" % h["feature_schema_version"])
    lines.append("")
    lines.append(femit("sentinel_mean_dyn", ms["mean_dyn"]))
    lines.append(femit("sentinel_scale_dyn", ms["scale_dyn"]))
    lines.append(femit("sentinel_mean_stat", ms["mean_stat"]))
    lines.append(femit("sentinel_scale_stat", ms["scale_stat"]))
    lines.append("")
    lines.append("/* NaN means \"not conformalised in this run\" (see model/quantize.py --")
    lines.append(" * happens when the calibration split has too few RUL points); firmware")
    lines.append(" * treats a NaN offset as 0 (no widening) rather than propagating NaN. */")
    for k in ("c_lo_soh", "c_hi_soh", "c_lo_rul", "c_hi_rul"):
        v = co[k]
        vstr = "nanf(\"\")" if isinstance(v, float) and math.isnan(v) else "%.9ff" % v
        lines.append("#define SENTINEL_%s %s" % (k.upper(), vstr))
    lines.append("")
    for k, v in gt.items():
        lines.append("#define SENTINEL_GRADE_%s %.9ff" % (k.upper(), v))
    lines.append("")
    lines.append("#endif /* SENTINEL_MODEL_STATS_H */")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
