// Part dictionary — IDs and roles exactly as in prototype/01 (I*, B*), prototype/03 (C*, X*), prototype/02 (J*).
export const PARTS = {
  I1: { name: 'Mains sense', grp: 'inverter', role: 'Small transformer + zero-cross detector. Produces the internal "mains present" signal and the panel LED.' },
  I2: { name: 'Changeover relay', grp: 'inverter', role: 'Switches AC-OUT between mains pass-through and bridge output. Transfer < 10 ms (Prime, UPS mode).' },
  I3: { name: 'Control board (SG3525 PWM)', grp: 'inverter', role: 'Analog PWM controller. Charge setpoints are fixed by resistor dividers / trim pot — no exposed bus.' },
  I4: { name: 'MOSFET bridge + heatsink', grp: 'inverter', role: 'Push-pull MOSFETs at 50 Hz. Run in reverse, the same bridge is the charger (I6).' },
  I5: { name: 'LF transformer 12 V ↔ 230 V', grp: 'inverter', role: 'Iron-core transformer. Steps battery 12 V up to 230 V AC; steps mains down when charging.' },
  I8: { name: 'Internal current shunt', grp: 'inverter', role: 'Shunt in the battery negative return. Sentinel-Embedded Kelvin-taps it (no external shunt needed).' },
  I10: { name: 'Cooling fan', grp: 'inverter', role: 'Thermal management of bridge and transformer.' },
  I11: { name: 'Front panel', grp: 'inverter', role: 'LEDs (mains / battery / charging / fault), LCD, buzzer, UPS/Normal switch, battery-type selector.' },
  C1: { name: 'ESP32-S3-WROOM-1-N16R8', grp: 'sentinel', role: 'Dual LX7 @ 240 MHz, 512 KB SRAM + 8 MB PSRAM, 16 MB flash. Runs EKF, int8 CNN (TFLM + ESP-NN), NILM, PQ, autopilot, health log — no network needed.' },
  C2: { name: 'MP2315 buck', grp: 'sentinel', role: 'Powers the board from the inverter 12 V rail (≈ 2.6 mA average).' },
  C3: { name: 'INA228 20-bit monitor', grp: 'sentinel', role: 'Reads the shunt mV drop (current) and battery voltage; 40-bit hardware coulomb counter.' },
  C4: { name: 'NTC input', grp: 'sentinel', role: 'Battery temperature → Arrhenius stress, charge compensation, EKF tables.' },
  C5: { name: 'AMC1311 isolated amplifier', grp: 'sentinel', role: 'Isolated ~4 kS/s AC-OUT voltage tap: half-cycle RMS, zero-cross, outage + sag/swell detection.' },
  C6: { name: 'ATM90E32AS metering AFE', grp: 'sentinel', role: 'True P, Q, S, PF at 3 Hz from the CT on AC-OUT — the NILM (Energy Coach) signal.' },
  C7: { name: 'ULN2003 coil driver', grp: 'sentinel', role: 'Sinks 12 V contactor-coil current, 4 channels. Coil off on reset = loads on.' },
  C8: { name: 'Supervisory timer', grp: 'sentinel', role: 'If the heartbeat pin stops toggling for 2 s it cuts the coil rail → all loads ON, whatever the firmware does.' },
  C9: { name: 'Medical jumper JP1', grp: 'sentinel', role: 'Hard-wires channel 4 coil to "never energise". The app cannot override hardware.' },
  C10: { name: 'DS3231 RTC + CR2032', grp: 'sentinel', role: 'Time of day through outages; timestamps the health log.' },
  C11: { name: 'ATECC608 secure element', grp: 'sentinel', role: 'Per-device ECDSA key that never leaves the chip; signs the hash-chained health log.' },
  C12: { name: 'PC817 optocoupler', grp: 'sentinel', role: 'Reads the inverter mode / mains-present line → vote s2 of the 2-of-3 outage detector.' },
  C13: { name: 'MCP4725 DAC (Embedded only)', grp: 'sentinel', role: 'Injects the charge-setpoint offset into the SG3525 feedback node; hardware clamp on the inverter side.' },
  C14: { name: 'USB-C · status LEDs · TVS', grp: 'sentinel', role: 'Provisioning, logs, firmware; TVS on every external line.' },
  X2: { name: 'NTC probe (battery)', grp: 'external', role: 'Strapped to the battery negative post — tracks electrolyte within ~2 °C.' },
  X4: { name: 'CT on AC-OUT live', grp: 'external', role: 'Split-core CT on the AC-OUT live conductor → ATM90E32AS current channel.' },
  X7: { name: 'NC contactor panel', grp: 'external', role: '4 × 25 A NC DIN contactors, 12 V coils. Coil energised = circuit open. Coil off = load ON.' },
  B1: { name: '12 V tubular battery, 150 Ah', grp: 'external', role: 'Flooded lead-acid, no electronics. V-Guard units accept one 12 V battery of 80–230 Ah.' },
  MCB: { name: 'Mains MCB (6 A)', grp: 'external', role: 'Flip it to create a real outage — exactly the finale bench demo.' },
};

export const CAM_PRESETS = {
  overview: { pos: [11, 10.5, 20], look: [3.4, 2.0, -1.2] },
  inside: { pos: [2.2, 7.6, 6.2], look: [0, 0.8, -0.2] },
  board: { pos: [1.35, 3.4, 1.95], look: [0.9, 1.35, 0.3] },
  relay: { pos: [2.6, 2.1, 2.3], look: [1.55, 0.8, 0.9] },
  loads: { pos: [9.5, 6.5, 11], look: [9, 2.5, -1] },
  battery: { pos: [-5, 5.5, 7], look: [-7, 2, 0] },
};
