/* AUTO-GENERATED by firmware/tools/make_model_stats.py from
 * model/artifacts_sim/sentinel_model_header.json -- do not hand-edit.
 * feature_schema_version=1 (must match features/schema.py, checked at
 * boot per design 04 §4 step 3). */
#ifndef SENTINEL_MODEL_STATS_H
#define SENTINEL_MODEL_STATS_H

#include <math.h>

#define SENTINEL_MODEL_FEATURE_SCHEMA_VERSION 1

static const float sentinel_mean_dyn[14] = {1.051630020f, 1.055047154f, 0.400034636f, 0.237204686f, 0.540207326f, 0.094346389f, 0.996569276f, 0.509199083f, 0.987330854f, 0.000000000f, 0.869016945f, 34.183067322f, 0.233543143f, -0.397365481f};
static const float sentinel_scale_dyn[14] = {0.166322932f, 0.294749260f, 0.340644032f, 0.110976808f, 0.066244714f, 0.289099663f, 0.075916983f, 0.231227517f, 0.082953252f, 1.000000000f, 0.314458370f, 5.457388401f, 0.305216253f, 0.015349015f};
static const float sentinel_mean_stat[6] = {10.254845619f, 1.099426150f, 10.218050957f, 0.020785781f, 0.000069093f, 0.106880441f};
static const float sentinel_scale_stat[6] = {5.561487675f, 0.388737708f, 6.564305305f, 0.068617590f, 0.000191760f, 0.064660892f};

/* NaN means "not conformalised in this run" (see model/quantize.py --
 * happens when the calibration split has too few RUL points); firmware
 * treats a NaN offset as 0 (no widening) rather than propagating NaN. */
#define SENTINEL_C_LO_SOH 13.831238638f
#define SENTINEL_C_HI_SOH 0.347141514f
#define SENTINEL_C_LO_RUL 0.533377005f
#define SENTINEL_C_HI_RUL 0.000000000f

#define SENTINEL_GRADE_HEALTHY_SOH_MIN 88.000000000f
#define SENTINEL_GRADE_HEALTHY_RUL_P10_MIN_WEEKS 26.000000000f
#define SENTINEL_GRADE_HEALTHY_REENTRY_SOH_MIN 90.000000000f
#define SENTINEL_GRADE_HEALTHY_REENTRY_RUL_P10_MIN_WEEKS 30.000000000f
#define SENTINEL_GRADE_DEGRADING_SOH_MIN 82.000000000f
#define SENTINEL_GRADE_DEGRADING_RUL_P10_MIN_WEEKS 8.000000000f

#endif /* SENTINEL_MODEL_STATS_H */
