"""healthlog/ — signed, append-only, hash-chained health log (design 09 §4, CONTRACTS §6)."""

from .healthlog import (
    EventType,
    Record,
    Checkpoint,
    HealthLogError,
    HealthLogWriter,
    SignFn,
    generate_keypair,
    export_public_key_raw,
    sign_hash,
    verify_hash_sig,
    make_sign_fn,
    parse_all,
    verify_chain,
    claim_bundle,
    derive_pseudonym,
    HEADER_SIZE,
    HASH_SIZE,
    SIG_SIZE,
    PUBKEY_SIZE,
    GENESIS_PREV_HASH,
    CHECKPOINT_SIZE,
)

__all__ = [
    "EventType",
    "Record",
    "Checkpoint",
    "HealthLogError",
    "HealthLogWriter",
    "SignFn",
    "generate_keypair",
    "export_public_key_raw",
    "sign_hash",
    "verify_hash_sig",
    "make_sign_fn",
    "parse_all",
    "verify_chain",
    "claim_bundle",
    "derive_pseudonym",
    "HEADER_SIZE",
    "HASH_SIZE",
    "SIG_SIZE",
    "PUBKEY_SIZE",
    "GENESIS_PREV_HASH",
    "CHECKPOINT_SIZE",
]
